### ISSUE TITLE
at <1162px width , make the right side menu turn into the cell phone hamburger menu (it currently does not change until smaller widths) thanks

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/AppersonAuto#53]
@Unesdala after you fix this, go back to the commonUtils and adjust the check for page width to scroll to the header now, thanks
@Unesdala also set the node version to 15 please, thanks `>=15.3.0`

**Comment by Unesdala** [comment]
@JoshuaVSherman - Are you talking about line 6 or 7 here? 7 is set to material-header by default.

**Comment by JoshuaVSherman** [comment]
The material header if width less than should be a higher amount now
